#!/bin/bash

alias astuce='if [[ -f .astuce ]] ; then cat .astuce ; else echo "Aucune astuce pour cette étape." ; fi'
alias perm="if [[ -f .perm ]] ; then source .perm ; else echo \"Le Permissionneur dit qu'il n'y a pas de boulot pour lui ici.\" ; fi"

echo
echo "Quelqu'un passe tout près de vous et glisse une petite feuille dans votre"
echo "poche. Ensuite il s’éloigne rapidement et rentre dans le répertoire 'suivez-moi'."
echo "Lisez le message"
echo
echo
echo "Pour avoir une astuce à l'étape où vous vous trouvez tapez la commande 'astuce'"
echo

chmod a-rwx ./suivez_moi/suivez_moi/repertoire_de_milieu/repertoire_de_gauche/garnison/parchemin.txt
chmod a-rwx ./suivez_moi/suivez_moi/repertoire_de_milieu/repertoire_de_gauche/garnison
chmod a-rwx ./suivez_moi/repertoire_de_droite/repertoire_de_droite/
chmod a-rwx ./suivez_moi/suivez_moi

export PS1='\u@\h \$ '
