CC = gcc
CFLAGS = -W -Wall 

puissance: puissance.c 
	$(CC) $(CFLAGS) puissance.c -o puissance -lm

Erasto: Erasto.c 
	$(CC) $(CFLAGS) Erasto.c -o Erasto -lm

clean:
	rm -f Erasto puissance

