exo1:	exo1.c
	gcc -Wall -o $@ $<

exo2:	exo2.c
	gcc -Wall -o $@ $<

exo3:	exo3.c
	gcc -Wall -o $@ $<

exo4:	exo4.c
		gcc -Wall -o $@ $<

exo5:	exo5.c
	gcc -Wall -o $@ $<

exo6:	exo6.c
	gcc -Wall -o $@ $<

r1:	exo1
	./exo1

r2:	exo2
	./exo2

r3:	exo3
	./exo3

r4:	exo4
	./exo4

r5:	exo5
	./exo5

r6:	exo6
	./exo6

clean:
	rm -f exo1 exo2 exo3 exo4 exo5 exo6
